### ISSUE TITLE
can this project run on openEuler22.09?

### ISSUE THREAD

**Issue by zhouyanchun** [kiosk404/openssl_tracer#1]
readelf -Ws /usr/lib64/libssl.so.1.1.1m | grep -i 'ssl_read'
   626: 0000000000039400   107 FUNC    GLOBAL DEFAULT   14 SSL_read@@OPENSSL_1_1_0
   727: 000000000003ce20   367 FUNC    GLOBAL DEFAULT   14 SSL_read_early_data@@OPENSSL_1_1_1
   777: 0000000000039470    24 FUNC    GLOBAL DEFAULT   14 SSL_read_ex@@OPENSSL_1_1_1

change binaryPath to const binaryPath = "/usr/lib64/libssl.so.1.1"
but openssl_tracer do not  get any ssl packet

[root@euler openssl_tracer]# ./openssl_trace
INFO[0000] target all process.                          
INFO[0000] successfully started, head over to /sys/kernel/debug/tracing/trace_pipe

**Comment by kiosk404** [comment]
I don't have an openEuler environment, but this operation is correct.
If no error is reported, It should be possible to get any ssl packet，may be used for encryption instead of /usr/lib64/libssl.so.1.1 
You can confirm whether it is correct
