### ISSUE TITLE
虽然技术上可以为IP地址配置HTTPS 但是实际中还是在域名通信中这个工具才能有效

### ISSUE THREAD

**Issue by cdxiaodong** [kiosk404/openssl_tracer#2]
虽然技术上可以为IP地址配置HTTPS 但是实际中还是在域名通信中这个工具才能有效
：因为ssl包的原因

所以ip间的ssl访问是无法捕捉到的

**Comment by kiosk404** [comment]
可以啊，IP还是域名没有影响，openssl 的加密原理不变，我本地试过访问 https://1.1.1.1 可以看到其 302 的明文

**Comment by cdxiaodong** [comment]
我后续使用的时候 用ssl和socket进行进程间通信然而无法openssltrace无法获取请求 请看下图
![image](https://github.com/kiosk404/openssl_tracer/assets/84082748/ece234f8-522f-42bc-875a-76d3e0899cd0)

![image](https://github.com/kiosk404/openssl_tracer/assets/84082748/8d9eea60-da51-44dc-aa91-8c6a5942b96a)
相关代码如下
se'rver。py
import socket
import ssl

HOST = 'localhost'
PORT = 12345

def handle_client(conn):
    with conn:
        print('Connected by', conn.getpeername())
        while True:
            data = conn.recv(1024)
            if not data:
                break
            print('Received:', data.decode())
            conn.sendall(b'Received: ' + data)

def main():
    context = ssl.create_default_context(ssl.Purpose.CLIENT_AUTH)
    context.load_cert_chain(certfile='server.crt', keyfile='server.key')

    with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as s:
        s.bind((HOST, PORT))
        s.listen(1)
        print("Server listening on {}:{}".format(HOST, PORT))

        with context.wrap_socket(s, server_side=True) as ssl_socket:
            while True:
                conn, addr = ssl_socket.accept()
                handle_client(conn)

if __name__ == "__main__":
    main()
    
    client。py
    import socket
import ssl

HOST = 'localhost'
PORT = 12345

def main():
    context = ssl.create_default_context(ssl.Purpose.SERVER_AUTH)
    context.check_hostname = False
    context.verify_mode = ssl.CERT_NONE

    with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as s:
        with context.wrap_socket(s, server_hostname=HOST) as ssl_socket:
            ssl_socket.connect((HOST, PORT))
            while True:
                message = input("Enter message: ")
                ssl_socket.sendall(message.encode())
                data = ssl_socket.recv(1024)
                print('Server response:', data.decode())

if __name__ == "__main__":
    main()
